### ISSUE TITLE
License

### ISSUE THREAD

**Issue by sbai** [civictechdc/ERDA#1]
We need to [choose a license](http://choosealicense.com/) for this project's source code.

**Comment by sbai** [comment]
If there are no objections, I'm going to add a [BSD license](http://choosealicense.com/licenses/bsd-3-clause/). This was one of the licenses Gabe and I preferred at the last discussion.

**Comment by gemarcano** [comment]
Is it the "new" three clause one? Then yes, I'm OK with it.

**Comment by sbai** [comment]
It's the three clause one, I'm not sure how "new" it is. I prefer it over the two clause license.

**Comment by gemarcano** [comment]
Yeah, I agree with the 3 clause over the 2 clause BSD license. Anyone else?

It's the three clause one, I'm not sure how "new" it is. I prefer it over
the two clause license.

—
Reply to this email directly or view it on
GitHubhttps://github.com/CodeForDC-ERDA/ERDA/issues/1#issuecomment-42758426
.
